# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb2cff9b30d15deaa5857eff93cc8dad7e9852a6f8a561fc5182e31a97dd6812b223b49394b1b46160c70b2bcfda25b1262d1c35c574af6b3a93ab0d96c1ebdc

test:
  secret_key_base: 991ddda3f8cd595bff18307be027bbbf9bb4db42ea74ac40c700a13c6891836aac64cf5e1e8505855f33e8767f5b6ad60fbaa06cb9723095c0bd2d18dfc0b1c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
